apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: erpnext
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://helm.erpnext.com
    chart: erpnext
    targetRevision: 5.0.6
    helm:
      releaseName: erpnext
      values: |
        site:
          host: erpnext.noschoixpourvous.com
          adminPassword: Wassim2011&@

        mariadb:
          enabled: true
          auth:
            rootPassword: auto
            database: erpnext
            username: erpnext
            password: auto
          primary:
            persistence:
              enabled: true
              storageClass: longhorn
              size: 20Gi

        persistence:
          worker:
            enabled: true
            storageClass: longhorn
            size: 20Gi

        ingress:
          enabled: true
          className: traefik
          hosts:
            - host: erpnext.noschoixpourvous.com
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - erpnext.noschoixpourvous.com

  destination:
    server: https://kubernetes.default.svc
    namespace: erpnext

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

