apiVersion: apps/v1
kind: Deployment
metadata:
  name: erpnext
  namespace: erpnext
spec:
  replicas: 1
  selector:
    matchLabels:
      app: erpnext
  template:
    metadata:
      labels:
        app: erpnext
    spec:

      initContainers:
        - name: wait-for-mariadb
          image: mariadb:10.6
          command:
            - sh
            - -c
            - |
              echo "⏳ Waiting for MariaDB..."
              until mysqladmin ping \
                -h"$DB_HOST" \
                -P"$DB_PORT" \
                -u"$DB_USER" \
                -p"$DB_PASSWORD" \
                --silent; do
                sleep 3
              done
              echo "✅ MariaDB is ready"
          envFrom:
            - secretRef:
                name: erpnext-secrets

      containers:
        - name: erpnext
          image: ton-dockerhub/erpnext-autobootstrap:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: erpnext-secrets

          livenessProbe:
            httpGet:
              path: /api/method/ping
              port: 8000
            initialDelaySeconds: 120
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /api/method/ping
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          volumeMounts:
            - name: sites
              mountPath: /home/frappe/frappe-bench/sites

      volumes:
        - name: sites
          persistentVolumeClaim:
            claimName: erpnext-sites
