apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: erpnext
  namespace: erpnext
spec:
  rules:
    - host: erpnext.noschoixpourvous.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: erpnext
                port:
                  number: 80
